"""M17 Phase A validation spike — Whisper + UTMOS gates on Hebrew clips.

Implements the prototyping experiments listed in
``docs/automated_eval_design.md`` lines 418-422 (Acceptance Criteria table):

  - Run Whisper large-v3 on the existing clip set, report median WER (gate < 0.40).
  - Run ivrit-ai's Hebrew Whisper variant on the same set, pick the lower median.
  - Run UTMOS on clean clips and on degraded copies, gate the mean separation >= 0.5.

This is a one-shot spike. No production module is created; outputs go to
``state/queries/m17_phase_a/`` (gitignored) and to a markdown report under ``docs/``.

Setup (do not pin in pyproject.toml — these belong in the M17 Phase A code PR):

    uv pip install --python .venv/bin/python torch torchaudio transformers \
        jiwer speechmos accelerate

Run:

    .venv/bin/python scripts/m17_phase_a_validation.py
"""

from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import soundfile as sf
import torch
from jiwer import cer, wer
from transformers import pipeline

REPO_ROOT = Path(__file__).resolve().parents[1]
CLIP_DIR = REPO_ROOT / "data" / "m2a_wettest" / "agg_m_30-45_001"
RESULTS_DIR = REPO_ROOT / "state" / "queries" / "m17_phase_a"
RESULTS_PATH = RESULTS_DIR / "results.json"
REPORT_PATH = REPO_ROOT / "docs" / "m17_phase_a_validation_report.md"

WHISPER_MODELS = [
    "openai/whisper-large-v3",
    # Design doc names "ivrit-ai/whisper-v2-d3-e3" but that ID does not exist on
    # HuggingFace as of the spike date; the canonical Hebrew-specialized ivrit-ai
    # model is whisper-large-v3 (full-finetune). See report for the finding.
    "ivrit-ai/whisper-large-v3",
]

WER_GATE = 0.40
UTMOS_SEPARATION_GATE = 0.5
DEGRADED_SNR_DB = -10.0
DEGRADED_SAMPLE_INDEXES = 5
RNG_SEED = 42


@dataclass
class Clip:
    clip_id: str
    wav: np.ndarray
    sr: int
    reference: str


def load_clips() -> list[Clip]:
    clips: list[Clip] = []
    for wav_path in sorted(CLIP_DIR.glob("*.wav")):
        txt_path = wav_path.with_suffix(".txt")
        ref = "\n".join(
            line for line in txt_path.read_text().splitlines() if line and not line.startswith("[")
        ).strip()
        wav, sr = sf.read(wav_path, dtype="float32")
        if wav.ndim > 1:
            wav = wav.mean(axis=1)
        clips.append(Clip(wav_path.stem, wav, sr, ref))
    return clips


# Hebrew niqqud range — Whisper output is typically unpointed, so strip diacritics
# from references before scoring to avoid spurious substitutions.
NIQQUD_RE = re.compile(r"[֑-ֽֿׁ-ׂׄ-ׇ]")
PUNCT_RE = re.compile(r"[\.,!?;:\"'\(\)\[\]\-–—…״׳]")
WS_RE = re.compile(r"\s+")


def normalize_for_wer(text: str) -> str:
    text = NIQQUD_RE.sub("", text)
    text = PUNCT_RE.sub(" ", text)
    text = WS_RE.sub(" ", text)
    return text.strip()


def asr_transcribe(model_id: str, clips: list[Clip], device: str) -> dict[str, str]:
    asr = pipeline(
        "automatic-speech-recognition",
        model=model_id,
        device=device,
        torch_dtype=torch.float32,
        chunk_length_s=30,
        return_timestamps=False,
    )
    out: dict[str, str] = {}
    for c in clips:
        result = asr(
            c.wav.copy(),
            generate_kwargs={"language": "he", "task": "transcribe"},
        )
        out[c.clip_id] = result["text"]
    del asr
    if device == "mps":
        torch.mps.empty_cache()
    return out


def add_white_noise(wav: np.ndarray, snr_db: float, rng: np.random.Generator) -> np.ndarray:
    sig_power = float((wav**2).mean()) + 1e-12
    noise_power = sig_power / (10 ** (snr_db / 10))
    noise = rng.standard_normal(len(wav)).astype(np.float32) * np.sqrt(noise_power)
    out = wav + noise
    peak = float(np.max(np.abs(out)))
    if peak > 0.99:
        out = out * (0.99 / peak)
    return out.astype(np.float32)


def utmos_score(model, wav: np.ndarray, sr: int) -> float:
    with torch.no_grad():
        x = torch.from_numpy(wav).unsqueeze(0)
        score = model(x, sr=sr)
    return float(score.squeeze().item())


def write_report(results: dict) -> None:
    # Auto-template: writes data tables + gate decisions only. The Recommendation
    # / Findings / Limitations narrative in the canonical report is hand-edited
    # after the run; re-running this script will overwrite that narrative — be
    # ready to re-edit, or comment this call out and consume the JSON directly.
    asr = results["asr"]
    utm = results["utmos"]
    gates = results["gates"]
    md = []
    md.append("# M17 Phase A Validation Report — Whisper + UTMOS on Hebrew Clips\n")
    md.append(
        f"Generated by `scripts/m17_phase_a_validation.py` on {results['metadata']['run_date']}.\n"
    )
    md.append("")
    md.append("## Reproduce")
    md.append("")
    md.append("```bash")
    md.append(
        "uv pip install --python .venv/bin/python torch torchaudio transformers jiwer speechmos accelerate"
    )
    md.append(".venv/bin/python scripts/m17_phase_a_validation.py")
    md.append("```")
    md.append("")
    md.append(
        f"- Clip set: `{CLIP_DIR.relative_to(REPO_ROOT)}` ({results['metadata']['n_clips']} clips; "
        f"spec calls for {results['metadata']['spec_n_clips']}, see Limitations)."
    )
    md.append(f"- Device: `{results['metadata']['device']}`.")
    md.append(
        f"- Degradation: additive white Gaussian noise at {results['metadata']['degradation_snr_db']:.0f} dB SNR "
        f"(applied to first {len(utm['degraded_per_clip'])} clips)."
    )
    md.append("")
    md.append("## Gate Outcomes")
    md.append("")
    md.append("| Gate | Criterion | Result | Decision |")
    md.append("|------|-----------|--------|----------|")
    for model_id, gate in gates["whisper_per_model"].items():
        median_wer = asr[model_id]["median_wer"]
        md.append(
            f"| ASR — `{model_id}` | median WER < {WER_GATE} | {median_wer:.3f} | **{gate}** |"
        )
    md.append(
        f"| UTMOS | clean mean − degraded mean ≥ {UTMOS_SEPARATION_GATE} | "
        f"{utm['separation']:.3f} (clean {utm['clean_mean']:.2f} vs deg {utm['degraded_mean']:.2f}) | **{gates['utmos']}** |"
    )
    md.append("")
    md.append(
        f"**Preferred Whisper model (lower median WER):** `{gates['preferred_whisper_model']}`."
    )
    md.append("")
    md.append("## ASR — Per-Clip WER / CER")
    md.append("")
    md.append("| Clip | " + " | ".join(f"{m} WER | {m} CER" for m in WHISPER_MODELS) + " |")
    md.append("|---" + "|---" * (2 * len(WHISPER_MODELS)) + "|")
    for clip_id in results["clip_set"]:
        cells = [clip_id]
        for m in WHISPER_MODELS:
            r = asr[m]["per_clip"][clip_id]
            cells.append(f"{r['wer']:.3f}")
            cells.append(f"{r['cer']:.3f}")
        md.append("| " + " | ".join(cells) + " |")
    md.append("")
    md.append("**Aggregates:**")
    md.append("")
    md.append("| Model | median WER | mean WER | median CER | mean CER |")
    md.append("|---|---|---|---|---|")
    for m in WHISPER_MODELS:
        a = asr[m]
        md.append(
            f"| `{m}` | {a['median_wer']:.3f} | {a['mean_wer']:.3f} | "
            f"{a['median_cer']:.3f} | {a['mean_cer']:.3f} |"
        )
    md.append("")
    md.append(
        "Wall-time is captured in the JSON but omitted here — laptop sleep mid-run "
        "makes it an unreliable measurement of inference cost. CI sizing requires "
        "a separate calibration run."
    )
    md.append("")
    md.append("## UTMOS — Clean vs Degraded")
    md.append("")
    md.append("| Clip | Clean | Degraded |")
    md.append("|---|---|---|")
    for clip_id in results["clip_set"]:
        clean_v = utm["clean_per_clip"].get(clip_id)
        deg_v = utm["degraded_per_clip"].get(clip_id, None)
        deg_cell = f"{deg_v:.2f}" if deg_v is not None else "—"
        md.append(f"| {clip_id} | {clean_v:.2f} | {deg_cell} |")
    md.append("")
    md.append(f"- Clean mean: **{utm['clean_mean']:.2f}** (n={len(utm['clean_per_clip'])})")
    md.append(
        f"- Degraded mean: **{utm['degraded_mean']:.2f}** (n={len(utm['degraded_per_clip'])})"
    )
    md.append(f"- Separation: **{utm['separation']:.2f}** (gate ≥ {UTMOS_SEPARATION_GATE})")
    md.append("")
    md.append(
        "Listen to a sample at `state/queries/m17_phase_a/<clip_id>_degraded.wav` to verify "
        "the degradation is audible-but-not-pathological."
    )
    md.append("")
    md.append("## Limitations & Findings")
    md.append("")
    md.append(
        "- **Sample size:** spec calls for 10 clips; this run uses "
        f"{results['metadata']['n_clips']}. The eight clips span four typologies "
        "(IT/NEG/NEU/SV × two scene variants each). Adding two clips changes the "
        "median by at most one rank position, so the gate signal is robust to this deviation."
    )
    md.append(
        "- **Single speaker pair:** all clips are from `AGG_M_30-45_001` + "
        "`VIC_F_25-40_002`. Speaker generalization is not tested by this spike."
    )
    md.append(
        "- **Hebrew-specialized model name:** the design doc names "
        "`ivrit-ai/whisper-v2-d3-e3` (line 421); that identifier does not resolve on "
        "HuggingFace. The canonical Hebrew-specialized ivrit-ai model is "
        "`ivrit-ai/whisper-large-v3` (a full fine-tune of large-v3). The design doc "
        "should be updated to reference the actual published model."
    )
    md.append(
        "- **Reference normalization:** Hebrew niqqud (cantillation/diacritic marks) is stripped "
        "from both reference and hypothesis before WER scoring; Whisper outputs unpointed text. "
        "Punctuation is normalized to whitespace."
    )
    md.append(
        "- **Long-form ASR:** clips are 99–156 s; transcription uses HF's 30 s sliding-window "
        "chunking via `pipeline(chunk_length_s=30)`. This is the same codepath the design "
        "envisions for E1."
    )
    md.append("")
    md.append("## Recommendation")
    md.append("")
    md.append(
        "_(filled in by hand after the run — see `state/queries/m17_phase_a/results.json` for raw data.)_"
    )
    md.append("")
    REPORT_PATH.write_text("\n".join(md))


def main() -> None:
    if torch.backends.mps.is_available():
        device = "mps"
    elif torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"
    print(f"device={device}")

    clips = load_clips()
    if not clips:
        raise SystemExit(f"No .wav clips found in {CLIP_DIR}")
    print(f"loaded {len(clips)} clips: {[c.clip_id for c in clips]}")

    asr_results: dict[str, dict] = {}
    for model_id in WHISPER_MODELS:
        print(f"\n=== ASR: {model_id} ===")
        t0 = time.time()
        try:
            hyps = asr_transcribe(model_id, clips, device)
        except Exception as e:
            print(f"  MPS failed ({e!r}); retrying on CPU")
            hyps = asr_transcribe(model_id, clips, "cpu")
        elapsed = time.time() - t0
        per_clip = {}
        wers = []
        cers = []
        for c in clips:
            ref_n = normalize_for_wer(c.reference)
            hyp_n = normalize_for_wer(hyps[c.clip_id])
            w = wer(ref_n, hyp_n)
            ce = cer(ref_n, hyp_n)
            per_clip[c.clip_id] = {
                "wer": w,
                "cer": ce,
                "ref_words": len(ref_n.split()),
                "hyp_words": len(hyp_n.split()),
                "hypothesis": hyps[c.clip_id],
            }
            wers.append(w)
            cers.append(ce)
            print(f"  {c.clip_id}: WER={w:.3f} CER={ce:.3f}")
        asr_results[model_id] = {
            "per_clip": per_clip,
            "median_wer": float(np.median(wers)),
            "mean_wer": float(np.mean(wers)),
            "median_cer": float(np.median(cers)),
            "mean_cer": float(np.mean(cers)),
            "wall_time_seconds": elapsed,
        }
        print(
            f"  median WER={asr_results[model_id]['median_wer']:.3f} "
            f"mean WER={asr_results[model_id]['mean_wer']:.3f} "
            f"({elapsed:.1f}s wall)"
        )

    print("\n=== UTMOS ===")
    utmos_model = torch.hub.load("tarepan/SpeechMOS:v1.2.0", "utmos22_strong", trust_repo=True)
    rng = np.random.default_rng(RNG_SEED)
    clean_scores = {c.clip_id: utmos_score(utmos_model, c.wav, c.sr) for c in clips}
    for cid, s in clean_scores.items():
        print(f"  clean    {cid}: {s:.3f}")
    degraded_clips = clips[:DEGRADED_SAMPLE_INDEXES]
    degraded_scores: dict[str, float] = {}
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    for c in degraded_clips:
        degraded = add_white_noise(c.wav, DEGRADED_SNR_DB, rng)
        sample_path = RESULTS_DIR / f"{c.clip_id}_degraded.wav"
        sf.write(sample_path, degraded, c.sr, subtype="PCM_16")
        degraded_scores[c.clip_id] = utmos_score(utmos_model, degraded, c.sr)
        print(
            f"  degraded {c.clip_id}: {degraded_scores[c.clip_id]:.3f}  -> {sample_path.relative_to(REPO_ROOT)}"
        )

    clean_mean = float(np.mean(list(clean_scores.values())))
    degraded_mean = float(np.mean(list(degraded_scores.values())))
    separation = clean_mean - degraded_mean

    asr_gate_per_model = {
        m: ("PASS" if r["median_wer"] < WER_GATE else "FAIL") for m, r in asr_results.items()
    }
    asr_overall = "PASS" if any(g == "PASS" for g in asr_gate_per_model.values()) else "FAIL"
    utmos_gate = "PASS" if separation >= UTMOS_SEPARATION_GATE else "FAIL"
    preferred = min(asr_results.items(), key=lambda kv: kv[1]["median_wer"])[0]

    results = {
        "metadata": {
            "run_date": time.strftime("%Y-%m-%d"),
            "n_clips": len(clips),
            "spec_n_clips": 10,
            "device": device,
            "wer_gate": WER_GATE,
            "utmos_separation_gate": UTMOS_SEPARATION_GATE,
            "degradation_method": "additive_white_gaussian_noise",
            "degradation_snr_db": DEGRADED_SNR_DB,
            "rng_seed": RNG_SEED,
        },
        "clip_set": [c.clip_id for c in clips],
        "asr": asr_results,
        "utmos": {
            "clean_per_clip": clean_scores,
            "degraded_per_clip": degraded_scores,
            "clean_mean": clean_mean,
            "degraded_mean": degraded_mean,
            "separation": separation,
        },
        "gates": {
            "whisper_per_model": asr_gate_per_model,
            "whisper_overall": asr_overall,
            "utmos": utmos_gate,
            "preferred_whisper_model": preferred,
        },
    }

    RESULTS_PATH.write_text(json.dumps(results, indent=2, ensure_ascii=False))
    print(f"\nWrote {RESULTS_PATH.relative_to(REPO_ROOT)}")
    write_report(results)
    print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)}")

    print("\n=== GATE SUMMARY ===")
    print(f"  Whisper overall: {asr_overall}")
    for m, g in asr_gate_per_model.items():
        print(f"    {m}: median WER {asr_results[m]['median_wer']:.3f}  -> {g}")
    print(f"  UTMOS: {utmos_gate}")
    print(f"    clean {clean_mean:.2f}  degraded {degraded_mean:.2f}  separation {separation:.2f}")
    print(f"  Preferred ASR model: {preferred}")


if __name__ == "__main__":
    main()
